app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as' => 'home',
    'uses' => 'HomeController@index'
]);

Route::get('/activity-rule', [
    'as' => 'activity-rule',
    'uses' => 'HomeController@activityRule'
]);

Route::get('/mission-status', [
    'as' => 'mission-status',
    'uses' => 'HomeController@missionStatus'
]);

Route::get('/privacy', [
    'as' => 'privacy',
    'uses' => 'HomeController@privacy'
]);

Route::get('/terms', [
    'as' => 'terms',
    'uses' => 'HomeController@terms'
]);

Route::get('/FAQ', [
    'as' => 'FAQ',
    'uses' => 'HomeController@FAQ'
]);

Route::get('/staff', [
    'as' => 'staff',
    'uses' => 'HomeController@staff'
]);

//Mission
Route::resource('mission', 'MissionController', [
    'except' => [
        'create'
    ]
]);

//Page
Route::post('page/sort', [
    'as' => 'page.sort',
    'uses' => 'PageController@sort'
]);
Route::resource('page', 'PageController', [
    'except' => [
        'index',
        'show'
    ]
]);

//Button
Route::post('button/sort', [
    'as' => 'button.sort',
    'uses' => 'ButtonController@sort'
]);
Route::resource('button', 'ButtonController', [
    'except' => [
        'index',
        'show'
    ]
]);

//Price
Route::get('price/grant', [
    'as' => 'price.grant',
    'uses' => 'PriceController@grant'
]);
Route::post('price/ajax-price', [
    'as' => 'price.ajax-price',
    'uses' => 'PriceController@ajaxPrice'
]);
Route::post('price/ajax-player', [
    'as' => 'price.ajax-player',
    'uses' => 'PriceController@ajaxPlayer'
]);
Route::post('price/ajax-grant', [
    'as' => 'price.ajax-grant',
    'uses' => 'PriceController@ajaxGrant'
]);
Route::resource('price', 'PriceController', [
    'except' => [
        'show'
    ]
]);

//Player
Route::get('player/export', [
    'as' => 'player.export',
    'uses' => 'PlayerController@export'
]);
Route::resource('player', 'PlayerController', [
    'only' => [
        'index'
    ]
]);

//Mail Notify
Route::get('mail-notify', [
    'as' => 'mail-notify.index',
    'uses' => 'MailNotifyController@index'
]);

Route::post('mail-notify/send', [
    'as' => 'mail-notify.send',
    'uses' => 'MailNotifyController@send'
]);

//Auth System
Route::controller('user', 'UserController', [
    'getIndex' => 'user.list',
    'getLogin' => 'user.login',
    'postLogin' => 'user.login',
    'getRegister' => 'user.register',
    'postRegister' => 'user.register',
    'getConfirm' => 'user.confirm',
    'getResend' => 'user.resend',
    'postResend' => 'user.resend',
    'getForgotPassword' => 'user.forgot-password',
    'postForgotPassword' => 'user.forgot-password',
    'getResetPassword' => 'user.reset-password',
    'postResetPassword' => 'user.reset-password',
    'getChangePassword' => 'user.change-password',
    'postChangePassword' => 'user.change-password',
    'getProfile' => 'user.profile',
    'getEditProfile' => 'user.edit-profile',
    'postEditProfile' => 'user.edit-profile',
    'getEditOtherProfile' => 'user.edit-other-profile',
    'postEditOtherProfile' => 'user.edit-other-profile',
    'getLogout' => 'user.logout'
]);

//API
Route::controller('api', 'ApiController', [
    'postIndex' => 'api.index',
    'postMission' => 'api.mission',
    'postPage' => 'api.page',
    'postButton' => 'api.button',
    'postResult' => 'api.result'
]);

//---------------------------------------------------------------------------------------
//寄送測試信
Route::post('send-test-mail', [
    'as' => 'send-test-mail',
    'uses' => 'SettingController@sendTestMail'
]);

//網站設定
Route::resource('setting', 'SettingController', ['except' => ['create', 'store', 'destroy']]);
//---------------------------------------------------------------------------------------

//Queue狀態
Route::get('queue-status', [
    'as' => 'queue-status',
    'uses' => 'QueueStatusController@index'
]);

//Log Viewer
Route::get('logs', [
    'as' => 'logs',
    'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index',
    'middleware' => 'role:admin'
]);

//Markdown API
Route::any('markdown', [
    'as' => 'markdown.preview',
    'uses' => 'MarkdownApiController@markdownPreview'
]);

//未定義路由
Route::get('{all}', [
    'as' => 'not-found',
    function () {
        abort(404);
    }
])->where('all', '.*');

app/Price.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Price extends Model
{
    protected $table = 'prices';
    protected $fillable = ['name', 'amount'];

    public function players()
    {
        return $this->hasMany('App\Player');
    }

    public function getLeftAttribute()
    {
        return $this->amount - $this->players->count();
    }

}

app/Http/Controllers/PriceController.php
<?php

namespace App\Http\Controllers;

use App\Player;
use App\Price;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class PriceController extends Controller
{
    public function __construct()
    {
        parent::__construct();
        //限管理員
        $this->middleware('role:admin');
        //限Ajax
        $this->middleware('ajax', [
            'only' => [
                'ajaxPrice'
            ]
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $prices = Price::all();
        return view('price.list')->with('prices', $prices);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('price.createOrEdit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'amount' => 'integer|min:0'
        ]);

        if ($validator->fails()) {
            return redirect()->route('price.create')
                ->withErrors($validator)
                ->withInput();
        }

        $price = Price::create([
            'name' => $request->get('name'),
            'amount' => $request->get('amount')
        ]);

        return redirect()->route('price.index')
            ->with('global', '獎品已新增');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $price = Price::find($id);
        if (!$price) {
            return redirect()->route('price.index')
                ->with('warning', '獎品不存在');
        }
        return view('price.createOrEdit')->with('price', $price);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $price = Price::find($id);
        if (!$price) {
            return redirect()->route('price.index')
                ->with('warning', '獎品不存在');
        }
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'amount' => 'integer|min:0'
        ]);

        if ($validator->fails()) {
            return redirect()->route('price.create')
                ->withErrors($validator)
                ->withInput();
        }

        $price->name = $request->get('name');
        $price->amount = $request->get('amount');
        $price->save();

        return redirect()->route('price.index')
            ->with('global', '獎品已更新');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $price = Price::find($id);
        if (!$price) {
            return redirect()->route('price.index')
                ->with('warning', '獎品不存在');
        }
        $price->delete();
        return redirect()->route('price.index')
            ->with('global', '獎品已刪除');
    }

    public function grant()
    {
        return view('price.grant');
    }

    //獎品資訊API（領獎用）
    public function ajaxPrice()
    {
        $prices = Price::all();
        $json = [];
        foreach ($prices as $price) {
            $json[] = [
                'id' => $price->id,
                'name' => $price->name,
                'amount' => $price->amount,
                'left' => $price->left
            ];
        }
        return \Response::json($json);
    }

    //玩家資訊API（領獎用）
    public function ajaxPlayer(Request $request)
    {
        $nid = $request->get('nid');
        $player = Player::find($nid);
        if (!$player) {
            $nid = substr($nid, 0, -1);
            $player = Player::find($nid);
        }
        if (!$player) {
            return \Response::json([]);
        }
        $json = [
            'nid' => $player->nid,
            'finishMissionCount' => $player->finishMissionCount,
            'finishAllMissions' => $player->finishAllMissions,
            'getPriceAt' => $player->get_price_at,
            'getPriceName' => ($player->get_price_at && $player->price) ? $player->price->name : '',
            'canGetPrice' => $player->canGetPrice,
        ];
        return \Response::json($json);
    }


    //領獎
    public function ajaxGrant(Request $request)
    {
        //檢查玩家
        $nid = $request->get('nid');
        $player = Player::find($nid);
        if (!$player) {
            $nid = substr($nid, 0, -1);
            $player = Player::find($nid);
        }
        if (!$player) {
            return \Response::json(['error' => '非有效玩家']);
        }

        if (!$player->canGetPrice) {
            return \Response::json(['error' => '該玩家無法領獎']);
        }
        //檢查獎項
        $priceId = $request->get('price_id');
        $price = Price::find($priceId);
        if (!$price) {
            return \Response::json(['error' => '獎品不存在']);
        }
        if (!$price->left) {
            return \Response::json(['error' => '該獎品已發送完畢']);
        }
        //記錄獎品
        $player->get_price_at = Carbon::now()->toDateTimeString();
        $player->price_id = $price->id;
        $player->save();

        $json = [
            'success' => true,
            'price' => $price->name
        ];

        return \Response::json($json);
    }
}

resources/views/price/createOrEdit.blade.php
@extends('app')

@section('title')@if(isset($price))編輯@else新增@endif獎品@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        @if(isset($price))
                            編輯獎品
                        @else
                            新增獎品
                        @endif
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            @if(isset($price))
                                {!! Form::model($price, ['route' => ['price.update', $price->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
                            @else
                                {!! Form::open(['route' => ['price.store'], 'class' => 'form-horizontal']) !!}
                            @endif
                            <div class="form-group has-feedback{{ ($errors->has('name'))?' has-error':'' }}">
                                {!! Form::label('name', '獎品名稱', ['class' => 'control-label col-md-2']) !!}
                                <div class="col-md-9">
                                    {!! Form::text('name', null, ['required', 'placeholder' => '請輸入獎品名稱', 'class' => 'form-control']) !!}
                                    @if($errors->has('name'))
                                        <span class="label label-danger">{{ $errors->first('name') }}</span>
                                        <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group has-feedback{{ ($errors->has('amount'))?' has-error':'' }}">
                                {!! Form::label('amount', '獎品數量', ['class' => 'control-label col-md-2']) !!}
                                <div class="col-md-9">
                                    {!! Form::number('amount', null, ['required', 'placeholder' => '請輸入獎品數量', 'class' => 'form-control', 'min' => 0, 'step' => 1]) !!}
                                    @if($errors->has('amount'))
                                        <span class="label label-danger">{{ $errors->first('amount') }}</span>
                                        <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-9 col-md-offset-2">
                                    {!! Form::submit('更新獎品', ['class' => 'btn btn-primary']) !!}
                                    {!! HTML::linkRoute('price.index', '返回', [], ['class' => 'btn btn-default']) !!}
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/price/grant.blade.php
@extends('app')

@section('title')獎品發放@endsection

@section('css')
    <style>
        #nid-box > input {
            font-size: 50px;
            height: auto;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        獎品發放
                        （<label title="學號輸入框自動取得焦點（建議開啟）">{!! Form::checkbox('autoFocus', true, true) !!} Auto Focus</label>）
                    </div>
                    <div class="panel-body">
                        {!! Form::open(['route' => 'price.grant', 'method' => 'get', 'id' => 'nid-box', 'class' => 'form-inline']) !!}
                        {!! Form::text('nid', null, ['class' => 'form-control','placeholder' => '請掃描學生證或輸入NID', 'autofocus', 'required']) !!}
                        {!! Form::submit('確認', ['class' => 'btn btn-primary']) !!}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        玩家資料
                    </div>
                    <div class="panel-body" id="player-box">

                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        發送獎品
                        <a href="javascript:void(0)" class="btn" id="priceUpdateButton"><span class="fa fa-refresh" id="priceUpdateIcon"></span> 更新</a>
                    </div>
                    <div class="panel-body">
                        <div class="alert alert-warning" role="alert">
                            <strong>請注意</strong>
                            <ul>
                                <li>若玩家未完成所有任務，將無法領獎</li>
                                <li>每位玩家限領獎一次</li>
                                <li>點擊獎項後立即記錄，且無法修改</li>
                            </ul>
                        </div>
                        <div id="price-box">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    {!! HTML::script('build-js/js.cookie.js') !!}
    <script>
        var $nidBox;
        var nid = '';
        var playerData = null;
        var autoFocus = true;
        function loadPrice(){
            var $priceBox = $('#price-box');
            var $priceUpdateButton = $('#priceUpdateButton');
            var $priceUpdateIcon = $('#priceUpdateIcon');
            $priceUpdateButton.attr("disabled", true);
            $priceUpdateIcon.addClass("fa-spin");
            $priceBox.html("讀取中...");
            {{-- 取得資料--}}
            var URLs = "{{ route('price.ajax-price' ) }}";
            $.ajax({
                url: URLs,
                data: {},
                headers: {
                    'X-CSRF-Token': "{{ Session::token() }}",
                    "Accept": "application/json"
                },
                type: "POST",
                dataType: "json",

                success: function (data) {
                    if($.isEmptyObject(data)){
                        $priceBox.html("無獎品資料");
                        return;
                    }
                    var buttonList = '';
                    if(playerData && !playerData.canGetPrice) {
                        buttonList += '<div class="alert alert-danger">該玩家無領獎資格</div>';
                    }
                    $.each(data, function(key, value){
                        var grantButton = '<div class="row" style="margin-bottom: 5px"><div class="col-md-12">';
                        if(value.left > 0) {
                            if(playerData && playerData.canGetPrice) {
                                grantButton += '<a href="javascript:void(0)" class="btn btn-lg btn-primary grant-button" data-id=' + value.id + '>' + value.name + '</a>';
                            }else{
                                grantButton += '<a href="javascript:void(0)" class="btn btn-lg btn-primary disabled" data-id=' + value.id + '>' + value.name + '</a>';
                            }
                            grantButton += ' <span class="text-info">剩餘：' + value.left + ' / ' + value.amount +'</span>';
                        }else{
                            grantButton += '<a href="javascript:void(0)" class="btn btn-lg btn-default disabled">' + value.name + '</a>';
                            grantButton += ' <span class="text-danger">剩餘：' + value.left + ' / ' + value.amount +'</span>';
                        }
                        grantButton += '</div></div>';
                        buttonList += grantButton;
                    });
                    $priceBox.html(buttonList);

                },
                error: function (xhr, ajaxOptions, thrownError) {
                    $priceBox.html("<span class=\"text-danger\"><span class=\"fa fa-times\"></span>發生錯誤：" + xhr.status + " " + thrownError + "</span>");
                },
                complete: function(data) {
                    $priceUpdateButton.attr("disabled", false);
                    $priceUpdateIcon.removeClass("fa-spin");
                }
            });
        }
        function loadPlayer(playerNid){
            var $playerBox = $('#player-box');
            $playerBox.html('讀取中...');
            var $priceBox = $('#price-box');
            $priceBox.html("等待玩家資料載入");
            playerData = null;
            {{-- 取得資料--}}
            var URLs = "{{ route('price.ajax-player' ) }}";
            $.ajax({
                url: URLs,
                data: {
                    nid:playerNid
                },
                headers: {
                    'X-CSRF-Token': "{{ Session::token() }}",
                    "Accept": "application/json"
                },
                type: "POST",
                dataType: "json",

                success: function (data) {
                    if($.isEmptyObject(data)){
                        $playerBox.html(playerNid + " - 無玩家資料");
                        return;
                    }
                    playerData = data;
                    playerDataText = '<div style="font-size: 20px">';
                    playerDataText += '<div class="row">';
                    playerDataText += '<div class="col-md-4 text-right">NID</div><div class="col-md-8">' + playerData.nid + '</div>';
                    playerDataText += '</div><div class="row">';
                    playerDataText += '<div class="col-md-4 text-right">準時完成任務數</div><div class="col-md-8">' + playerData.finishMissionCount + ' / {{ \App\Mission::where('require', '=', true)->count() }}</div>';
                    playerDataText += '</div><div class="row">';
                    playerDataText += '<div class="col-md-4 text-right">完成所有任務</div><div class="col-md-8">' + ((playerData.finishAllMissions)?'O':'X') + '</div>';
                    playerDataText += '</div><div class="row">';
                    playerDataText += '<div class="col-md-4 text-right">領獎時間</div><div class="col-md-8">' + ((playerData.getPriceAt)?playerData.getPriceAt:'-') + '</div>';
                    playerDataText += '</div><div class="row">';
                    playerDataText += '<div class="col-md-4 text-right">領獎獎項</div><div class="col-md-8">' + ((playerData.getPriceAt)?playerData.getPriceName:'-') + '</div>';
                    playerDataText += '</div><div class="row">';
                    playerDataText += '<div class="col-md-4 text-right">可領獎？</div><div class="col-md-8">' + ((playerData.canGetPrice)?'O':'X') + '</div>';
                    playerDataText += '</div>';
                    playerDataText += '</div>';
                    $playerBox.html(playerDataText);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    $playerBox.html("<span class=\"text-danger\"><span class=\"fa fa-times\"></span>發生錯誤：" + xhr.status + " " + thrownError + "</span>");
                },
                complete: function(data) {
                    loadPrice();
                }
            });
        }
        function sendPrice(priceId){
            var URLs = "{{ route('price.ajax-grant' ) }}";
            $.ajax({
                url: URLs,
                data: {
                    nid: playerData.nid,
                    price_id: priceId
                },
                headers: {
                    'X-CSRF-Token': "{{ Session::token() }}",
                    "Accept": "application/json"
                },
                type: "POST",
                dataType: "json",

                success: function (data) {
                    if(data.success){
                        show_message('success',"成功發送獎品：" + data.price);
                    } else {
                        show_message('error',"發生錯誤：" + data.error);
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    show_message('error',"發生錯誤：" + xhr.status + " " + thrownError);
                },
                complete: function(data) {
                    loadPlayer(nid);
                }
            });
        }
        $('#nid-box').submit(function(event){
            nid = $nidBox.val();
            loadPlayer(nid);
            $nidBox.val('');
            $nidBox.focus();
            return false;
        });
        $('#priceUpdateButton').click(function(){
            loadPrice();
        });
        $('input[name=autoFocus]').click(function () {
            var isChecked = $(this).is(':checked');
            Cookies.set('autoFocus', isChecked);
            autoFocus = isChecked;
        });
        $(document).on( 'click', '.grant-button', function (event) {
            if(nid.length < 1){
                show_message('error', '未輸入學號');
                return;
            }
            if(playerData == null){
                show_message('error', '非有效玩家');
                return;
            }
            if(!playerData.canGetPrice){
                show_message('error', '該玩家無法領獎');
                return;
            }
            var confirmResult = confirm('確定要發送 ' + $(event.target).text() + ' 嗎？');
            if(!confirmResult){
                return;
            }
            sendPrice($(this).data('id'));
        });
        $(document).on( 'click', '*', function (event) {
            if(!autoFocus){
                return;
            }
            $nidBox.focus();
        });
        $(document).ready(function(){
            $nidBox = $('input[name=nid]');
            //AutoFocus
            if(typeof Cookies.get('autoFocus') !== 'undefined' && Cookies.get('autoFocus') == 'false'){
                autoFocus = false;
                $('input[name=autoFocus]').attr('checked', false);
            }
            loadPrice();
        });
    </script>
@endsection

resources/views/price/list.blade.php
@extends('app')

@section('title')獎品管理@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        獎品管理
                    </div>
                    <div class="panel-body">
                        <div class="pull-right">
                            {!! link_to_route('price.grant', '獎品發放', [], ['class' => 'btn btn-primary']) !!}
                            {!! link_to_route('price.create', '新增獎品', [], ['class' => 'btn btn-primary']) !!}
                        </div>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>獎品名稱</th>
                                    <th>總數量</th>
                                    <th>送出數量</th>
                                    <th>剩餘數量</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($prices as $price)
                                    <tr>
                                        <td>{{ $price->name }}</td>
                                        <td>{{ $price->amount }}</td>
                                        <td>{{ $price->players->count() }}</td>
                                        <td>{{ $price->left }}</td>
                                        <td>
                                            {!! link_to_route('price.edit', '編輯', $price->id, ['class' => 'btn btn-default']) !!}
                                            {!! Form::open(['route' => ['price.destroy', $price->id], 'style' => 'display: inline', 'method' => 'DELETE', 'onSubmit' => "return confirm('確定要刪除此獎品嗎？');"]) !!}
                                            {!! Form::submit('刪除', ['class' => 'btn btn-danger']) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5" class="text-center">
                                            暫無獎品
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection